

USE Company
GO

CREATE TABLE Department(
	DeptNo INT NOT NULL,
	DeptName VARCHAR(20) NOT NULL,
	Location VARCHAR(20) NOT NULL
);

CREATE TABLE Employee(
	Id INT NOT NULL,
	EmpName VARCHAR(20) NOT NULL,
	DeptNo INT,
	Age INT NOT NULL,
	Salary INT NOT NULL
);

ALTER TABLE Employee ADD PRIMARY KEY (Id);
ALTER TABLE Department ADD PRIMARY KEY(DeptNo);
ALTER TABLE Employee ADD FOREIGN KEY (DeptNo) REFERENCES Department (DeptNo);

INSERT INTO Employee VALUES (101, 'SUJIT', 301, 26, 45000);
INSERT INTO Employee VALUES (102, 'SURAJ', 302, 25, 50000);
INSERT INTO Employee VALUES (103, 'VAIBHAV', 302, 28, 55000);
INSERT INTO Employee VALUES (104, 'SARANG', 303, 27, 60000);

INSERT INTO Department VALUES (301,'SALES','PUNE');
INSERT INTO Department VALUES (302,'MARKETING','MUMBAI');
INSERT INTO Department VALUES (303,'RESEARCH','BANGLORE');





